server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file:${PWD}/config-repo

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        native:
          searchLocations: file:/config-repo
